# Generated by Django 2.2.5 on 2019-10-01 07:13

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('location_x', models.DecimalField(decimal_places=5, max_digits=5)),
                ('localion_y', models.DecimalField(decimal_places=5, max_digits=5)),
                ('zone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('notification', django.contrib.postgres.fields.jsonb.JSONField()),
                ('not_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('encryptedId', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserConnections',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('connected_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_user_id', to='users.User')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetials',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
                ('gender', models.TextField()),
                ('bio', models.TextField()),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('last_login', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfoMapping',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('notification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Notifications')),
                ('user_connections_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserConnections')),
                ('user_detials_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserDetials')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
                ('user_location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Location')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('prefer_gender', models.TextField()),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('min_distance', models.IntegerField()),
                ('max_distance', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='userinfomapping',
            name='user_preferences_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserPreferences'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
