# Generated by Django 2.2.5 on 2019-10-02 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191001_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userconnections',
            name='connected_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userconnections',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinfomapping',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
