# Generated by Django 2.2.5 on 2019-10-03 13:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191003_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetials',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None),
        ),
        migrations.AlterField(
            model_name='userdetials',
            name='last_login',
            field=models.DateTimeField(blank=True),
        ),
    ]
