# Generated by Django 2.2.5 on 2019-10-05 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191003_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='localion_y',
            new_name='location_y',
        ),
        migrations.AlterField(
            model_name='userinfomapping',
            name='notification_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Notifications'),
        ),
        migrations.AlterField(
            model_name='userinfomapping',
            name='user_connections_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.UserConnections'),
        ),
        migrations.AlterField(
            model_name='userinfomapping',
            name='user_detials_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.UserDetials'),
        ),
        migrations.AlterField(
            model_name='userinfomapping',
            name='user_location_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Location'),
        ),
        migrations.AlterField(
            model_name='userinfomapping',
            name='user_preferences_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.UserPreferences'),
        ),
    ]
