# Generated by Django 2.2.5 on 2019-10-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191005_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_x',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_y',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
