# Generated by Django 2.2.5 on 2019-10-05 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191005_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconnections',
            name='connected_user_id',
        ),
        migrations.RemoveField(
            model_name='userconnections',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='userinfomapping',
            name='notification_id',
        ),
        migrations.RemoveField(
            model_name='userinfomapping',
            name='user_connections_id',
        ),
        migrations.AlterField(
            model_name='userinfomapping',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.DeleteModel(
            name='UserConnections',
        ),
    ]
