# Generated by Django 2.2.5 on 2019-10-05 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191005_1325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetials',
            new_name='UserDetails',
        ),
        migrations.RenameField(
            model_name='userinfomapping',
            old_name='user_detials_id',
            new_name='user_details_id',
        ),
    ]
