# Generated by Django 2.2.5 on 2019-10-05 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20191005_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfomapping',
            name='user_details_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserDetails'),
        ),
        migrations.AlterField(
            model_name='userinfomapping',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinfomapping',
            name='user_location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Location'),
        ),
        migrations.AlterField(
            model_name='userinfomapping',
            name='user_preferences_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserPreferences'),
        ),
    ]
